language: go
go:
  - 1.7
install:
  - go get github.com/bwmarrin/discordgo
  - go get github.com/BurntSushi/toml
  - go get github.com/Sirupsen/logrus
  - go get gopkg.in/alecthomas/kingpin.v2
  - go get -v .
  - go get github.com/golang/lint/golint
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -v -race ./...
